#!/usr/bin/bash

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# add nix profile to PATH early (so we can find nu)
if [ -d "$HOME/.nix-profile/bin" ]; then
    export PATH="$HOME/.nix-profile/bin:$PATH"
fi

# source universal environment setup
if command -v nu > /dev/null && [ -x "$HOME/.local/bin/_env-setup" ]; then
    eval "$($HOME/.local/bin/_env-setup bash)"
fi

# add brew shellenv for additional vars (HOMEBREW_PREFIX, etc.)
for brew in /opt/homebrew /home/linuxbrew/.linuxbrew; do
    if [ -d $brew ]; then
        eval "$(${brew}/bin/brew shellenv)"
    fi
done

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi

unset rc

# make bash play dumb unless intentionally launched by user
if [[ -z "${BASH_NOAUTO}" ]] && [[ "${SSH_CONNECTION}" || "${TERM_PROGRAM}" || "${WSL_DISTRO_NAME}" ]] && tty -s; then
    # reset home if WSL or OrbStack launched from windows home
    if type -P rg > /dev/null && ([[ "${WSL_DISTRO_NAME}" ]] || echo "$BROWSER" | rg -q orbstack) && echo "$(pwd)" | rg -q "/Users/[^/]+$"; then
        cd "$HOME"
    fi

    # if we've not launched from fish and fish exists, exec fish
    if echo "${SHELL}" | grep -q bash && type -P fish > /dev/null; then
        exec fish -l
    fi

    PS1="$(hostname -s)@$(whoami)> "

    # hook starship
    if tty -s && type starship &> /dev/null; then
        eval "$(starship init bash)"
    fi
fi
