#!/usr/bin/bash

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi

unset rc

# add brew to PATH
for brew in /opt/homebrew /home/linuxbrew/.linuxbrew; do
    if [ -d $brew ]; then
        eval "$(${brew}/bin/brew shellenv)"
    fi
done

# add nix-profile to PATH
for nix in /nix/var/nix/profiles/default/bin $HOME/.nix-profile/bin /run/wrappers/bin; do
    if [ -d "$nix" ]; then
        PATH="${nix}:${PATH}"
    fi
done

# make bash play dumb unless intentionally launched by user
if [[ "${SSH_CONNECTION}" || "${TERM_PROGRAM}" || "${WSL_DISTRO_NAME}" ]] && tty -s; then
    # reset home if WSL launched from windows home
    if type -P rg > /dev/null && [[ "${WSL_DISTRO_NAME}" ]] && echo "$(pwd)" | rg -q "/Users/[^/]+$"; then
        cd "$HOME"
    fi

    # if we've not launched from fish and fish exists, exec fish
    if echo "${SHELL}" | grep -q bash && tty -s && type -P fish > /dev/null; then
        exec fish -l
    fi

    PS1="$(hostname -s)@$(whoami)> "

    # hook starship
    if tty -s && type starship &> /dev/null; then
        eval "$(starship init bash)"
    fi
fi
