#!/usr/bin/bash

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
    for rc in ~/.bashrc.d/*; do
        if [ -f "$rc" ]; then
            . "$rc"
        fi
    done
fi

unset rc

# make bash play dumb unless intentionally launched by user
if [ "${SSH_CONNECTION}${TERM_PROGRAM}" ] && tty -s; then
    # if we've not launched from fish and fish exists, exec fish
    if echo "${SHELL}" | grep -q bash && tty -s && type -P fish > /dev/null; then
        exec fish -l
    fi

    # add brew to PATH
    for brew in /opt/homebrew /home/linuxbrew/.linuxbrew; do
        if [ -d $brew ]; then
            eval "$(${brew}/bin/brew shellenv)"
        fi
    done

    # hook starship
    if tty -s && type starship &> /dev/null; then
    eval "$(starship init bash)"
    fi
fi
