#!/bin/sh

if type git > /dev/null 2> /dev/null; then
    git pull
fi

# main directory
ln -vsf $PWD/gitconfig ~/.gitconfig
ln -vsf $PWD/vimrc ~/.vimrc
ln -vsf $PWD/yaourtrc ~/.yaourtrc

# config directory
mkdir -vp ~/.config
ln -vsf $PWD/redshift.conf ~/.config/
# fish
mkdir -vp ~/.config/fish
ln -vsf $PWD/fish/config.fish ~/.config/fish/
# fontconfig
mkdir -vp ~/.config/fontconfig
ln -vsf $PWD/fontconfig.xml ~/.config/fontconfig/fonts.conf
# dunst
mkdir -vp ~/.config/dunst
ln -vsf $PWD/dunstrc ~/.config/dunst

# ssh
mkdir -vp ~/.ssh
ln -vsf $PWD/authorized_keys ~/.ssh/
