#!/bin/sh

if type git > /dev/null 2> /dev/null; then
    git pull
fi

# main directory
ln -vsf $PWD/gitconfig ~/.gitconfig
ln -vsf $PWD/vimrc ~/.vimrc
ln -vsf $PWD/yaourtrc ~/.yaourtrc
ln -vsf $PWD/xonshrc.py ~/.xonshrc

# config directory
mkdir -vp ~/.config
ln -vsf $PWD/redshift.conf ~/.config/
ln -vsf $PWD/alacritty.yml ~/.config/
# git
ln -vsfT $PWD/git ~/.config/git
# fish
ln -vsfT $PWD/fish ~/.config/fish
# fontconfig
mkdir -vp ~/.config/fontconfig
ln -vsf $PWD/fontconfig.xml ~/.config/fontconfig/fonts.conf
# dunst
mkdir -vp ~/.config/dunst
ln -vsf $PWD/dunstrc ~/.config/dunst
# waybar
ln -vsfT $PWD/waybar ~/.config/waybar
# mako
ln -vsfT $PWD/mako ~/.config/mako

# ssh
mkdir -vp ~/.ssh
cp -v --remove-destination $PWD/authorized_keys ~/.ssh/
