#!/usr/bin/env python3

import os
import shutil
import subprocess

stashed = False
changes = False

root = subprocess.check_output(
    ("git", "rev-parse", "--show-toplevel"),
    text=True,
).strip()

# attempt to run pre-commit
if shutil.which("pre-commit") and os.path.isfile(
    os.path.join(root, ".pre-commit-config.yaml")
):
    subprocess.check_call(("pre-commit", "run"))
