#!/usr/bin/env python

import json
import subprocess
from re import template
from sys import argv

# read commit template
commit_msg = []
with open(argv[1], "r") as f:
    commit_msg = f.read().split("\n")

# conventional commits
if commit_msg[0].startswith("Merge"):
    commit_msg[0] = f"chore: {commit_msg[0].lower()}"
if commit_msg[0].startswith("Revert"):
    commit_msg[0] = f"fix: {commit_msg[0].lower()}"

# taskwarrior
try:
    tasks = json.loads(subprocess.getoutput("task export +ACTIVE and ticket.any:"))
    for task in tasks:
        commit_msg.append(
            f'ref: {task.get("ticket")} ({task.get("project").removeprefix("Work.").replace(".", "-")}) {task.get("description")}\n'
        )
except:
    pass

# write back
with open(argv[1], "w") as f:
    f.write("\n".join(commit_msg))
