format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$fossil_branch\
$fossil_metrics\
$kubernetes\
$direnv\
$env_var\
${custom.timew}\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$netns\
$shell\
$character"""

[git_status]
format = "([$all_status$ahead_behind]($style) )"
stashed = ""                                     # I abuse stashes way too much for a symbol for them to be meaningful to me
deleted = "-"
conflicted = "‼️"
modified = "~"

[sudo]
disabled = false

[time]
disabled = false
format = "[$time]($style) "
style = "purple"
time_format = "%R"

[shell]
disabled = false
fish_indicator = ""

[env_var.https_proxy]
symbol="🌐"
style="red bold"
format="with [$symbol$env_value]($style) "

[docker_context]
disabled = true

[kubernetes]
disabled = false
symbol = "⎈ "
format = '[$symbol$context(/$namespace)]($style) '

[custom.timew]
#shell = ["bash", "-c"]
command = "timew get dom.active.duration"
when = "[ \"$(timew get dom.active)\" = '1' ]"
#when = true
