[git_status]
format = "([$all_status$ahead_behind]($style) )"
stashed = ""                                     # I abuse stashes way too much for a symbol for them to be meaningful to me
deleted = "-"
conflicted = "‼️"
modified = "~"

[sudo]
disabled = false

[time]
disabled = false
format = "[$time]($style) "
style = "purple"
time_format = "%R"
